[package]
name = "platform"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
game = { path = "../game" }
platform-api = { path = "../platform-api" }

[target.'cfg(target_os = "linux")'.dependencies]
renderer-wgpu = { path = "../renderer-wgpu" }
pollster = { version = "0.4.0", default-features = false }
rustix = { version = "1.1.5", default-features = false, features = ["std", "fs"] }
winit = { version = "0.30.13", default-features = false, features = ["x11", "rwh_06"] }

[lints]
workspace = true
