[package]
name = "game-memory"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]

[lints.rust]
warnings = "deny"
unsafe_code = "allow"
unsafe_op_in_unsafe_fn = "deny"
elided_lifetimes_in_paths = "deny"
unreachable_pub = "deny"

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
missing_errors_doc = "allow"
missing_panics_doc = "allow"
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
allow_attributes = "deny"
infinite_loop = "deny"
undocumented_unsafe_blocks = "deny"
multiple_unsafe_ops_per_block = "deny"
unnecessary_safety_comment = "deny"
unnecessary_safety_doc = "deny"
